# Generated by Django 4.2.20 on 2026-05-06 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0002_add_user_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BastionHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='跳板机名称')),
                ('host', models.GenericIPAddressField(verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, verbose_name='私钥')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('memo', models.TextField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '跳板机',
                'verbose_name_plural': '跳板机',
            },
        ),
        migrations.CreateModel(
            name='BatchCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('target_hosts', models.TextField(help_text='IP范围或逗号分隔的IP列表，如: 192.168.1.1-254 或 192.168.1.2', verbose_name='目标主机')),
                ('target_port', models.IntegerField(default=22, verbose_name='目标SSH端口')),
                ('target_username', models.CharField(default='root', max_length=100, verbose_name='目标用户名')),
                ('target_password', models.CharField(blank=True, max_length=255, verbose_name='目标密码')),
                ('target_private_key', models.TextField(blank=True, verbose_name='目标私钥')),
                ('command', models.TextField(help_text='要执行的命令，多条命令请用分号分隔', verbose_name='命令内容')),
                ('run_as_root', models.BooleanField(default=True, verbose_name='以root权限执行')),
                ('jump_via_bastion', models.BooleanField(default=False, help_text='勾选后通过跳板机跳转时使用SSH密钥免密登录（跳板机需配置密钥交换）；不勾选则读取目标服务器的密码进行连接', verbose_name='通过跳板机免密跳转')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='上次运行时间')),
                ('last_run_status', models.CharField(blank=True, choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=20, verbose_name='上次运行状态')),
                ('memo', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bastion', models.ForeignKey(blank=True, help_text='留空则直连目标服务器', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.bastionhost', verbose_name='跳板机')),
                ('target_group', models.ForeignKey(blank=True, help_text='选择资产组后，将在该组内的所有主机上执行命令', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.hostgroup', verbose_name='目标资产组')),
            ],
            options={
                'verbose_name': '批量执行命令',
                'verbose_name_plural': '批量执行命令',
            },
        ),
        migrations.CreateModel(
            name='BatchCommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('hostname', models.CharField(blank=True, max_length=50, verbose_name='主机名')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=20, verbose_name='状态')),
                ('command_output', models.TextField(blank=True, verbose_name='命令输出')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('run_time', models.DateTimeField(auto_now_add=True, verbose_name='运行时间')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.batchcommand', verbose_name='命令任务')),
            ],
            options={
                'verbose_name': '命令执行历史',
                'verbose_name_plural': '命令执行历史',
                'ordering': ['-run_time'],
            },
        ),
        migrations.CreateModel(
            name='CollectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField(verbose_name='主机IP')),
                ('hostname', models.CharField(blank=True, max_length=50, verbose_name='主机名')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=20, verbose_name='状态')),
                ('cpu_info', models.CharField(blank=True, max_length=200, verbose_name='CPU信息')),
                ('memory_info', models.CharField(blank=True, max_length=100, verbose_name='内存信息')),
                ('disk_info', models.TextField(blank=True, verbose_name='硬盘信息')),
                ('gpu_info', models.CharField(blank=True, max_length=200, verbose_name='GPU信息')),
                ('os_info', models.CharField(blank=True, max_length=100, verbose_name='操作系统')),
                ('sn_info', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('collect_time', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '采集历史',
                'verbose_name_plural': '采集历史',
                'ordering': ['-collect_time'],
            },
        ),
        migrations.CreateModel(
            name='CollectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('target_hosts', models.TextField(help_text='IP范围或逗号分隔的IP列表，如: 192.168.1.1-254 或 192.168.1.2', verbose_name='目标主机')),
                ('target_port', models.IntegerField(default=22, verbose_name='目标SSH端口')),
                ('target_username', models.CharField(default='root', max_length=100, verbose_name='目标用户名')),
                ('target_password', models.CharField(blank=True, max_length=255, verbose_name='目标密码')),
                ('target_private_key', models.TextField(blank=True, verbose_name='目标私钥')),
                ('collect_online_only', models.BooleanField(default=True, verbose_name='仅采集在线主机')),
                ('jump_via_bastion', models.BooleanField(default=False, help_text='勾选后通过跳板机跳转时使用SSH密钥免密登录（跳板机需配置密钥交换）；不勾选则读取目标服务器的密码进行连接', verbose_name='通过跳板机免密跳转')),
                ('is_auto_collect', models.BooleanField(default=False, verbose_name='启用自动采集')),
                ('cron_expression', models.CharField(blank=True, help_text='格式: 分 时 日 月 周, 如: 0 2 * * * 表示每天凌晨2点', max_length=100, verbose_name='定时表达式')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_collect_time', models.DateTimeField(blank=True, null=True, verbose_name='上次采集时间')),
                ('last_collect_status', models.CharField(blank=True, choices=[('success', '成功'), ('failed', '失败'), ('partial', '部分成功')], max_length=20, verbose_name='上次采集状态')),
                ('memo', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_hostname', models.BooleanField(default=True, verbose_name='更新主机名')),
                ('update_os', models.BooleanField(default=True, verbose_name='更新操作系统')),
                ('update_cpu', models.BooleanField(default=True, verbose_name='更新CPU信息')),
                ('update_memory', models.BooleanField(default=True, verbose_name='更新内存')),
                ('update_disk', models.BooleanField(default=False, verbose_name='更新硬盘')),
                ('update_gpu', models.BooleanField(default=True, verbose_name='更新GPU信息')),
                ('update_device_info', models.BooleanField(default=True, verbose_name='更新设备信息')),
                ('update_sn', models.BooleanField(default=True, verbose_name='更新序列号')),
                ('bastion', models.ForeignKey(blank=True, help_text='留空则直连目标服务器', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.bastionhost', verbose_name='跳板机')),
                ('target_group', models.ForeignKey(blank=True, help_text='选择资产组后，将采集该组内的所有主机', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.hostgroup', verbose_name='目标资产组')),
            ],
            options={
                'verbose_name': '采集任务',
                'verbose_name_plural': '采集任务',
            },
        ),
        migrations.CreateModel(
            name='SSHConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置名称')),
                ('host', models.GenericIPAddressField(verbose_name='SSH服务器IP')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='密码')),
                ('private_key', models.TextField(blank=True, verbose_name='私钥内容')),
                ('collect_asset_types', models.CharField(default='1,2,3', help_text='逗号分隔的类型ID: 1=物理机, 2=虚拟机, 3=容器, 6=其他', max_length=50, verbose_name='采集资产类型')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用状态')),
                ('memo', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '目标服务器',
                'verbose_name_plural': '目标服务器',
            },
        ),
        migrations.CreateModel(
            name='StaticAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=50, verbose_name='序号')),
                ('asset_no', models.CharField(blank=True, max_length=100, verbose_name='服务器资产编号')),
                ('cabinet', models.CharField(blank=True, max_length=100, verbose_name='机柜')),
                ('start_u', models.CharField(blank=True, max_length=10, verbose_name='开始U数')),
                ('end_u', models.CharField(blank=True, max_length=10, verbose_name='结束U数')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='使用部门/团队（负责人）')),
                ('server_type', models.CharField(blank=True, max_length=100, verbose_name='服务器类型')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='联系人/责任人/使用人')),
                ('device_model', models.CharField(blank=True, max_length=100, verbose_name='服务器品牌型号')),
                ('server_model', models.CharField(blank=True, max_length=200, verbose_name='服务器机型（CPU/GPU卡型数量）')),
                ('power_rating', models.CharField(blank=True, max_length=50, verbose_name='服务器额定功率')),
                ('memo', models.TextField(blank=True, max_length=200, verbose_name='备注')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='状态')),
                ('hostgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.hostgroup', verbose_name='所属资产组')),
            ],
            options={
                'verbose_name': '静态资产',
                'verbose_name_plural': '静态资产',
            },
        ),
        migrations.DeleteModel(
            name='InterFace',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
        migrations.AlterModelOptions(
            name='ipsource',
            options={'verbose_name': 'IP地址来源', 'verbose_name_plural': 'IP地址来源'},
        ),
        migrations.RemoveField(
            model_name='host',
            name='position',
        ),
        migrations.RemoveField(
            model_name='host',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='ipsource',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='ipsource',
            name='net',
        ),
        migrations.RemoveField(
            model_name='ipsource',
            name='subnet',
        ),
        migrations.AddField(
            model_name='host',
            name='bm_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='带外管理IP'),
        ),
        migrations.AddField(
            model_name='host',
            name='cabinet_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在机柜位置'),
        ),
        migrations.AddField(
            model_name='host',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, verbose_name='联系人/责任人'),
        ),
        migrations.AddField(
            model_name='host',
            name='cpu_cores',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPU核数'),
        ),
        migrations.AddField(
            model_name='host',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属部门/团队'),
        ),
        migrations.AddField(
            model_name='host',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='设备品牌型号'),
        ),
        migrations.AddField(
            model_name='host',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=200, verbose_name='GPU型号'),
        ),
        migrations.AddField(
            model_name='host',
            name='gpu_num',
            field=models.CharField(blank=True, max_length=100, verbose_name='GPU内存'),
        ),
        migrations.AddField(
            model_name='host',
            name='is_auto_update',
            field=models.BooleanField(default=False, verbose_name='自动更新'),
        ),
        migrations.AddField(
            model_name='host',
            name='last_collect_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次采集时间'),
        ),
        migrations.AddField(
            model_name='host',
            name='power_rating',
            field=models.CharField(blank=True, max_length=30, verbose_name='额定功率(W)'),
        ),
        migrations.AddField(
            model_name='idc',
            name='area',
            field=models.CharField(blank=True, max_length=100, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='idc',
            name='operator',
            field=models.CharField(blank=True, max_length=100, verbose_name='运营商'),
        ),
        migrations.AddField(
            model_name='ipsource',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.cabinet', verbose_name='所在机柜'),
        ),
        migrations.AddField(
            model_name='ipsource',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='ipsource',
            name='ip_segment',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP段'),
        ),
        migrations.AddField(
            model_name='ipsource',
            name='memo',
            field=models.TextField(blank=True, max_length=200, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='ipsource',
            name='switch_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='交换机名称'),
        ),
        migrations.AddField(
            model_name='ipsource',
            name='switch_port',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='交换机端口'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_model',
            field=models.CharField(blank=True, max_length=200, verbose_name='CPU型号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='other_ip',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='其它IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='sn',
            field=models.CharField(blank=True, max_length=60, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(blank=True, choices=[('1', '使用中'), ('2', '未使用'), ('3', '故障'), ('4', '其他')], max_length=30, null=True, verbose_name='设备状态'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='bandwidth',
            field=models.CharField(blank=True, max_length=30, verbose_name='带宽'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='memo',
            field=models.TextField(blank=True, max_length=200, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='tel',
            field=models.CharField(blank=True, max_length=30, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userprofiles', to='cmdb.role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collecthistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.collecttask', verbose_name='采集任务'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='cmdb.sshconfig', verbose_name='目标服务器'),
        ),
    ]
