# Generated by Django 4.2.20 on 2026-05-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_bastionhost_batchcommand_batchcommandhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticAssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='静态资产组名')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='描述')),
            ],
            options={
                'verbose_name': '静态资产组',
                'verbose_name_plural': '静态资产组',
            },
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '动态资产组', 'verbose_name_plural': '动态资产组'},
        ),
        migrations.RemoveField(
            model_name='staticasset',
            name='hostgroup',
        ),
        migrations.AddField(
            model_name='staticasset',
            name='asset_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.staticassetgroup', verbose_name='所属静态资产组'),
        ),
    ]
