# Generated by Django 4.2.20 on 2026-05-06 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0004_staticassetgroup_alter_hostgroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('full', '全量备份'), ('incremental', '增量备份')], max_length=20, verbose_name='备份类型')),
                ('backup_name', models.CharField(max_length=255, verbose_name='备份名称')),
                ('backup_path', models.CharField(blank=True, max_length=500, verbose_name='备份路径')),
                ('file_size', models.CharField(blank=True, max_length=50, verbose_name='文件大小')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('running', '运行中')], max_length=20, verbose_name='备份状态')),
                ('backup_time', models.DateTimeField(auto_now_add=True, verbose_name='备份时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '备份记录',
                'verbose_name_plural': '备份记录',
                'ordering': ['-backup_time'],
            },
        ),
    ]
