# Generated by Django 4.2.20 on 2026-05-14 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_operationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型代码')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '备件类型',
                'verbose_name_plural': '备件类型管理',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(blank=True, help_text='如 HD-2025-001，可选', max_length=100, null=True, verbose_name='备件资产编号')),
                ('name', models.CharField(max_length=100, verbose_name='备件名称')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='大小/规格')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='序列号')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('images', models.TextField(blank=True, verbose_name='图片路径JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.spareparttype', verbose_name='备件类型')),
            ],
            options={
                'verbose_name': '备件',
                'verbose_name_plural': '备件管理',
            },
        ),
    ]
