# Generated by Django 4.2.20 on 2026-05-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_operationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(blank=True, help_text='如 HD-2025-001，可选', max_length=100, null=True, verbose_name='备件资产编号')),
                ('type', models.CharField(choices=[('hard_drive', '硬盘'), ('memory', '内存'), ('power_supply', '电源'), ('fan', '风扇'), ('other', '其他')], max_length=50, verbose_name='备件类型')),
                ('related_asset_no', models.CharField(blank=True, help_text='从静态资产库中选择', max_length=100, null=True, verbose_name='关联服务器资产编号')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('cabinet_location', models.CharField(blank=True, max_length=100, verbose_name='机柜位置')),
                ('allocate_date', models.DateField(blank=True, null=True, verbose_name='分配时间')),
                ('remove_date', models.DateField(blank=True, null=True, verbose_name='下架时间')),
                ('failure_reason', models.TextField(blank=True, verbose_name='故障原因')),
                ('images', models.TextField(blank=True, verbose_name='图片路径JSON')),
                ('status', models.CharField(choices=[('available', '可用'), ('failed', '故障下架')], default='available', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '备件',
                'verbose_name_plural': '备件管理',
            },
        ),
    ]
