# Generated by Django 4.2.20 on 2026-05-14 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0007_spareparttype_sparepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(blank=True, help_text='如 PCIe Slot 1, DIMM A1, Disk Bay 2', max_length=100, verbose_name='槽位')),
                ('is_removable', models.BooleanField(default=True, verbose_name='是否可拆卸')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('child_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='cmdb.host', verbose_name='子资产（组件）')),
                ('parent_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relations', to='cmdb.host', verbose_name='主资产（服务器）')),
            ],
            options={
                'verbose_name': '资产关系',
                'verbose_name_plural': '资产关系管理',
                'unique_together': {('parent_asset', 'slot')},
            },
        ),
        migrations.AddField(
            model_name='sparepart',
            name='installed_host_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='安装主机ID'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='installed_slot',
            field=models.CharField(blank=True, max_length=100, verbose_name='安装槽位'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='is_installed',
            field=models.BooleanField(default=False, verbose_name='是否已安装'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='status',
            field=models.CharField(choices=[('in_stock', '库存中'), ('installed', '已安装'), ('scrapped', '已报废'), ('maintenance', '维修中')], default='in_stock', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('purchase', '采购'), ('deploy', '上架'), ('maintenance', '维护'), ('repair', '维修'), ('uninstall', '下架'), ('reinstall', '重新上架'), ('scrap', '报废')], max_length=20, verbose_name='事件类型')),
                ('event_time', models.DateTimeField(verbose_name='事件时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='cmdb.host', verbose_name='资产')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '生命周期事件',
                'verbose_name_plural': '生命周期管理',
            },
        ),
        migrations.CreateModel(
            name='InstallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_time', models.DateTimeField(verbose_name='安装时间')),
                ('uninstall_time', models.DateTimeField(blank=True, null=True, verbose_name='拆卸时间')),
                ('operation_type', models.CharField(choices=[('install', '安装'), ('uninstall', '拆卸'), ('replacement', '更换'), ('expansion', '扩容'), ('maintenance', '维护')], max_length=20, verbose_name='操作类型')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('asset_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_histories', to='cmdb.assetrelation', verbose_name='资产关系')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '安装历史',
                'verbose_name_plural': '安装历史管理',
            },
        ),
    ]
