# Generated by Django 4.2.20 on 2026-05-14 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_add_asset_relation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='installhistory',
            name='child_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install_histories_as_child', to='cmdb.host', verbose_name='子资产'),
        ),
        migrations.AddField(
            model_name='installhistory',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install_histories_as_parent', to='cmdb.host', verbose_name='主资产'),
        ),
        migrations.AddField(
            model_name='installhistory',
            name='purchase_order_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采购单号'),
        ),
        migrations.AddField(
            model_name='installhistory',
            name='source_type',
            field=models.CharField(choices=[('spare', '备件库'), ('direct_purchase', '直接采购')], default='direct_purchase', max_length=20, verbose_name='来源类型'),
        ),
        migrations.AlterField(
            model_name='installhistory',
            name='asset_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install_histories', to='cmdb.assetrelation', verbose_name='资产关系'),
        ),
        migrations.AlterField(
            model_name='installhistory',
            name='operation_type',
            field=models.CharField(choices=[('install', '安装'), ('uninstall', '拆卸'), ('replacement', '更换'), ('expansion', '扩容'), ('maintenance', '维护'), ('direct_install', '直换')], max_length=20, verbose_name='操作类型'),
        ),
    ]
