# Generated by Django 4.2.20 on 2026-05-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_add_fields_to_install_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='是否已退库'),
        ),
        migrations.AddField(
            model_name='assetrelation',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='退库时间'),
        ),
    ]
