# Generated by Django 4.2.20 on 2026-05-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_assetrelation_is_returned_assetrelation_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='images',
            field=models.TextField(blank=True, verbose_name='图片路径JSON'),
        ),
    ]
