# Generated by Django 4.2.20 on 2026-05-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_add_images_to_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='品牌'),
        ),
    ]
