# Generated by Django 4.2.20 on 2026-05-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0012_add_brand_to_host'),
    ]

    operations = [
    ]
