# Generated by Django 4.2.20 on 2026-05-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_add_images_to_officepart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='是否为管理员'),
        ),
    ]
