# Generated by Django 4.2.20 on 2026-06-11 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0016_add_cabinet_field_to_ipsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配件名称')),
                ('category', models.CharField(choices=[('cpu', 'CPU'), ('motherboard', '主板'), ('gpu', '显卡'), ('memory', '内存'), ('hdd', '机械硬盘'), ('ssd', '固态硬盘'), ('power', '电源'), ('chassis', '机箱'), ('monitor', '显示器'), ('keyboard', '键盘'), ('mouse', '鼠标'), ('webcam', '摄像头'), ('headset', '耳机/麦克风'), ('network_card', '网卡'), ('other', '其他')], default='other', max_length=20, verbose_name='配件分类')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('size', models.CharField(blank=True, help_text='如: 500GB, 8GB DDR4', max_length=100, verbose_name='大小/规格')),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='资产编号')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SN')),
                ('source_computer', models.CharField(blank=True, help_text='如: PC-2024-001', max_length=200, verbose_name='来源办公电脑')),
                ('status', models.CharField(choices=[('new', '全新'), ('in_stock', '在库'), ('used', '拆机良品'), ('returned', '已退库'), ('faulty', '故障'), ('retired', '待报废')], default='in_stock', max_length=20, verbose_name='当前状态')),
                ('dismantle_date', models.DateField(blank=True, null=True, verbose_name='拆机时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('images', models.TextField(blank=True, verbose_name='图片路径JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '办公机配件',
                'verbose_name_plural': '办公机配件管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficePartReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='退库单号')),
                ('return_person', models.CharField(max_length=100, verbose_name='退库人')),
                ('return_date', models.DateField(verbose_name='退库日期')),
                ('return_reason', models.CharField(choices=[('damaged', '损坏'), ('replacement', '更换'), ('normal_return', '正常归还')], max_length=20, verbose_name='退库原因')),
                ('health_check', models.IntegerField(blank=True, null=True, verbose_name='硬盘健康度(%)')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已入库'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='处理状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_part_return_orders', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.officepart', verbose_name='关联配件')),
            ],
            options={
                'verbose_name': '配件退库单',
                'verbose_name_plural': '配件退库单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficePartFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('in', '入库'), ('issue', '发放'), ('return', '退库'), ('reissue', '再次发放')], max_length=20, verbose_name='流转类型')),
                ('operator_name', models.CharField(blank=True, max_length=100, verbose_name='操作人姓名')),
                ('recipient', models.CharField(blank=True, max_length=100, verbose_name='领用人')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('return_reason', models.CharField(blank=True, choices=[('damaged', '损坏'), ('replacement', '更换'), ('normal_return', '正常归还')], max_length=20, verbose_name='退库原因')),
                ('health_check', models.IntegerField(blank=True, null=True, verbose_name='硬盘健康度(%)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='仓库位置')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='cmdb.officepart', verbose_name='关联配件')),
            ],
            options={
                'verbose_name': '配件流转记录',
                'verbose_name_plural': '配件流转记录管理',
                'ordering': ['created_at'],
            },
        ),
    ]
