# Generated by Django 4.2.20 on 2026-06-03 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '0016_add_cabinet_field_to_ipsource'),
    ]

    operations = [
        # OfficePart table already exists, only create new tables
        migrations.CreateModel(
            name='OfficePartReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='退库单号')),
                ('return_person', models.CharField(max_length=100, verbose_name='退库人')),
                ('return_date', models.DateField(verbose_name='退库日期')),
                ('return_reason', models.CharField(choices=[('damaged', '损坏'), ('replacement', '更换'), ('normal_return', '正常归还')], max_length=20, verbose_name='退库原因')),
                ('health_check', models.IntegerField(blank=True, null=True, verbose_name='硬盘健康度(%)')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已入库'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='处理状态')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reject_reason', models.TextField(blank=True, verbose_name='驳回原因')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_part_return_orders', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.officepart', verbose_name='关联配件')),
            ],
            options={
                'verbose_name': '配件退库单',
                'verbose_name_plural': '配件退库单管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficePartFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('in', '入库'), ('issue', '发放'), ('return', '退库'), ('reissue', '再次发放')], max_length=20, verbose_name='流转类型')),
                ('operator_name', models.CharField(blank=True, max_length=100, verbose_name='操作人姓名')),
                ('recipient', models.CharField(blank=True, max_length=100, verbose_name='领用人')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='所属部门')),
                ('return_reason', models.CharField(blank=True, choices=[('damaged', '损坏'), ('replacement', '更换'), ('normal_return', '正常归还')], max_length=20, verbose_name='退库原因')),
                ('health_check', models.IntegerField(blank=True, null=True, verbose_name='硬盘健康度(%)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='仓库位置')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='cmdb.officepart', verbose_name='关联配件')),
            ],
            options={
                'verbose_name': '配件流转记录',
                'verbose_name_plural': '配件流转记录管理',
                'ordering': ['created_at'],
            },
        ),
    ]
