# Generated by Django 4.2.20 on 2026-06-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_officepart_officepartreturnorder_officepartflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配件名称')),
                ('category', models.CharField(choices=[('cpu', 'CPU'), ('motherboard', '主板'), ('gpu', '显卡'), ('memory', '内存'), ('hdd', '机械硬盘'), ('ssd', '固态硬盘'), ('power', '电源'), ('chassis', '机箱'), ('monitor', '显示器'), ('keyboard', '键盘'), ('mouse', '鼠标'), ('webcam', '摄像头'), ('headset', '耳机/麦克风'), ('network_card', '网卡'), ('other', '其他')], default='other', max_length=20, verbose_name='配件分类')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('size', models.CharField(blank=True, help_text='如: 500GB, 8GB DDR4', max_length=100, verbose_name='大小/规格')),
                ('asset_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='资产编号')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SN')),
                ('source_computer', models.CharField(blank=True, help_text='如: PC-2024-001', max_length=200, verbose_name='来源办公电脑')),
                ('status', models.CharField(choices=[('new', '全新'), ('in_stock', '在库'), ('used', '拆机良品'), ('returned', '已退库'), ('faulty', '故障'), ('retired', '待报废')], default='in_stock', max_length=20, verbose_name='当前状态')),
                ('dismantle_date', models.DateField(blank=True, null=True, verbose_name='拆机时间')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='存放位置')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='购买日期')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('images', models.TextField(blank=True, verbose_name='图片路径JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '办公机配件',
                'verbose_name_plural': '办公机配件管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
