# Generated by Django 4.2.20 on 2026-06-11 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0017_officepart_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrelation',
            name='child_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_relations', to='cmdb.host', verbose_name='子资产（组件）'),
        ),
    ]
