# Generated by Django 4.2.20 on 2026-06-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0018_change_assetrelation_cascade_to_setnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installhistory',
            name='child_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='install_histories_as_child', to='cmdb.host', verbose_name='子资产'),
        ),
    ]
