# Generated by Django 4.2.20 on 2026-06-11 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0019_change_installhistory_cascade_to_setnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrelation',
            name='parent_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_relations', to='cmdb.host', verbose_name='主资产（服务器）'),
        ),
    ]
