# Generated by Django 4.2.20 on 2026-06-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0020_change_assetrelation_parent_cascade_to_setnull'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='child_asset_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='子资产型号'),
        ),
        migrations.AddField(
            model_name='assetrelation',
            name='child_asset_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='子资产名称'),
        ),
        migrations.AddField(
            model_name='assetrelation',
            name='child_asset_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='子资产编号'),
        ),
        migrations.AddField(
            model_name='assetrelation',
            name='child_asset_sn',
            field=models.CharField(blank=True, max_length=100, verbose_name='子资产序列号'),
        ),
        migrations.AddField(
            model_name='assetrelation',
            name='parent_asset_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='主资产名称'),
        ),
        migrations.AddField(
            model_name='assetrelation',
            name='parent_asset_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='主资产编号'),
        ),
    ]
