# Generated by Django 4.2.20 on 2026-06-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0021_add_assetrelation_redundant_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='child_asset_images',
            field=models.TextField(blank=True, verbose_name='子资产图片（JSON格式）'),
        ),
    ]
