# Generated by Django 4.2.20 on 2026-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0022_add_child_asset_images_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='child_asset_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='子资产类型'),
        ),
    ]
